# Choose profile at runtime, e.g.
#   ./gradlew :mnim2377-spring:bootRun -Dspring.profiles.active=jdbc
#   ./gradlew :mnim2377-spring:bootRun -Dspring.profiles.active=jpa
#
spring.profiles.active=jdbc

