spring.profiles.active=in-memory
spring.datasource.username=postgres
spring.datasource.password=Victus
spring.datasource.url=jdbc:postgresql://localhost:5432/idde
spring.datasource.driver-class-name=org.postgresql.Driver