spring.application.name=gyak-spring
app.greetings-message=Hello developer
spring.profiles.active=logger

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5436/idde_db_gyak
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=idde_user_gyak
spring.datasource.password=idde_password_gyak

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true