
services:
  postgres:
    image: postgres:16
    container_name: iddegyak-springboot-postgres
    restart: always
    environment:
      POSTGRES_USER: idde_user_gyak
      POSTGRES_PASSWORD: idde_password_gyak
      POSTGRES_DB: idde_db_gyak
    ports:
      - "5436:5432"
    volumes:
      - postgres_idde_gyak_data:/var/lib/postgresql/data
      - ./src/main/java/edu/idde/mnim2377/database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_idde_gyak_data:
